stages:
  - build
  - deploy

before_script:
  - source shared/env.sh
  - chmod +x shared/before-script.sh && ./shared/before-script.sh

after_script:
  - source shared/env.sh
  - chmod +x shared/after-script.sh && ./shared/after-script.sh

# Auto run on being trigger by source code CI/CD
auto-build:
  rules:
    - if: $GLOBAL_CI == "off" || $GROUP_CI == "off" || $REPO_CI == "off"
      when: never
    - if: $CI_PIPELINE_SOURCE == "trigger" && $STAGE == "build"
      when: always
    - when: never
  tags:
    - prod-build
  environment: production
  stage: build
  variables:
    SHARED_PATH: /builds/${CI_PROJECT_PATH}
  script:
    - chmod +x $BUILD_PATH/*.sh
    - $BUILD_PATH/build.sh

auto-deploy:
  tags:
    - prod-deploy
  rules:
    - if: $GLOBAL_CI == "off" || $GROUP_CI == "off" || $REPO_CI == "off"
      when: never
    - if: $CI_PIPELINE_SOURCE == "trigger" && $STAGE == "deploy"
      when: always
    - when: never
  environment: production
  image: 172.28.8.132:5002/system/k8s-config/helm:3.7.2
  stage: deploy
  script:
    - mkdir -m 600 -p /root/.kube
    - chmod +x $DEPLOY_PATH/config/get-config.sh && $DEPLOY_PATH/config/get-config.sh
    - helm upgrade --install --set image.tag=${IMAGE_TAG} --set image.repository=${CI_REGISTRY_URI} --set logging.output.logstashPrefix=${LOGSTASH_PREFIX} --wait -n $NAMESPACE $HELM_RELEASE_NAME $DEPLOY_PATH/helm

# Manually
manual-build:
  tags:
    - prod-build
  environment: production
  stage: build
  variables:
    SHARED_PATH: /builds/$CI_PROJECT_PATH
    DOCKER_TAG: dev-d9a4a7ef
  script:
    - chmod +x $BUILD_PATH/*.sh
    - $BUILD_PATH/build.sh
  when: manual

manual-deploy:
  variables:
    DOCKER_TAG: dev-d9a4a7ef
  tags:
    - prod-deploy
  environment: production
  image: 172.28.8.132:5002/system/k8s-config/helm:3.7.2
  stage: deploy
  script:
    - mkdir -m 600 -p /root/.kube
    - chmod +x $DEPLOY_PATH/config/get-config.sh && $DEPLOY_PATH/config/get-config.sh
    - helm upgrade --install --set image.tag=${IMAGE_TAG} --set image.repository=${CI_REGISTRY_URI} --set logging.output.logstashPrefix=${LOGSTASH_PREFIX} --wait -n $NAMESPACE $HELM_RELEASE_NAME $DEPLOY_PATH/helm
  when: manual
